service: notion-blog
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  notionBlogPublish:
    handler: handler.notion_to_blog
    events:
      - httpApi:
          path: /api/v1
          method: get
      - schedule: rate(60 minutes)
  notionBlugUpdate:
    handler: handler.notion_to_devto_update
    events:
      - httpApi:
          path: /api/v2
          method: get
      - schedule: rate(60 minutes)

    environment:
      NOTION_API_KEY: <YOUR_NOTION_API_KEY>
      DEV_TO_API_KEY: <YOUR-DEV_TO_API_KEY>
      NOTION_DATABASE_ID: <YOUR_NOTION_DATABASE_ID>